name: Build GSI

on:
  workflow_dispatch:
    inputs:
      rom_url:
        description: 'Paste the link to the stock ROM (zip file)'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y git aria2 python3 python3-pip unzip
          pip3 install --upgrade pip

      - name: Clone ErfanGSI Builder
        run: git clone --depth=1 https://github.com/erfanoabdi/ErfanGSIs.git ErfanGSIs

      - name: Build GSI
        run: |
          cd ErfanGSIs
          bash setup.sh ${{ github.event.inputs.rom_url }}

      - name: Upload GSI
        uses: actions/upload-artifact@v2
        with:
          name: GSI
          path: ErfanGSIs/output/*.img
