name: Build GSI

on:
  workflow_dispatch:
    inputs:
      rom_url:
        description: 'Paste the link to the stock ROM (zip file)'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies (without python2)
        run: |
          sudo apt update
          sudo apt install -y git aria2 python3 python3-pip unzip build-essential wget
          pip3 install --upgrade pip

      - name: Install Python 2.7 manually
        run: |
          wget https://www.python.org/ftp/python/2.7.18/Python-2.7.18.tgz
          tar xzf Python-2.7.18.tgz
          cd Python-2.7.18
          ./configure --enable-optimizations
          make -j$(nproc)
          sudo make altinstall  # This installs as python2.7 (not as 'python2')

      - name: Clone ErfanGSI Builder
        run: git clone --depth=1 https://github.com/erfanoabdi/ErfanGSIs.git ErfanGSIs

      - name: Build GSI
        run: |
          cd ErfanGSIs
          bash setup.sh ${{ github.event.inputs.rom_url }}

      - name: Upload GSI artifact
        uses: actions/upload-artifact@v3
        with:
          name: GSI
          path: ErfanGSIs/output
