name: Build GSI

on:
  workflow_dispatch:
    inputs:
      rom_url:
        description: 'Paste the link to the stock ROM (zip file)'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y git aria2 python3 python3-pip unzip build-essential wget simg2img img2simg
          pip3 install --upgrade pip

      - name: Install Python 2.7 manually
        run: |
          wget https://www.python.org/ftp/python/2.7.18/Python-2.7.18.tgz
          tar xzf Python-2.7.18.tgz
          cd Python-2.7.18
          ./configure --enable-optimizations
          make -j$(nproc)
          sudo make altinstall
          # Create symlink for python2 compatibility
          sudo ln -s /usr/local/bin/python2.7 /usr/local/bin/python2

      - name: Clone ErfanGSI Builder
        run: git clone --depth=1 https://github.com/erfanoabdi/ErfanGSIs.git ErfanGSIs

      - name: Download and verify ROM
        run: |
          aria2c -x 16 -s 16 "${{ github.event.inputs.rom_url }}" -o rom.zip
          unzip -l rom.zip || { echo "Invalid ROM zip file"; exit 1; }

      - name: Build GSI
        run: |
          cd ErfanGSIs
          bash setup.sh ../rom.zip

      - name: Upload GSI artifact
        uses: actions/upload-artifact@v4
        with:
          name: gsi-output
          path: ErfanGSIs/output/*.img
