name: Convert GSI to VNDKLITE

on:
  workflow_dispatch:
    inputs:
      ARCH:
        description: 'Architecture (64 or 32)'
        required: true
        default: '64'
        type: choice
        options:
          - 64
          - 32
      IMAGE_URL:
        description: 'Direct URL to system.img.xz'
        required: true

jobs:
  convert:
    runs-on: ubuntu-latest
    env:
      ARCH: ${{ github.event.inputs.ARCH }}
      IMAGE_URL: ${{ github.event.inputs.IMAGE_URL }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y attr e2fsprogs wget unzip android-sdk-libsparse-utils

      - name: Install Python 2.7 manually
        run: |
          wget https://www.python.org/ftp/python/2.7.18/Python-2.7.18.tgz
          tar xzf Python-2.7.18.tgz
          cd Python-2.7.18
          ./configure --enable-optimizations
          make -j$(nproc)
          sudo make altinstall
          sudo ln -s /usr/local/bin/python2.7 /usr/local/bin/python2

            - name: Download and extract system.img.xz
        run: |
          wget "$IMAGE_URL" -O system.img.xz
          unxz system.img.xz
          mv system.img system.img.raw
          # Check if sparse, convert if needed
          if file system.img.raw | grep -q "Android sparse image"; then
            simg2img system.img.raw system.img
          else
            mv system.img.raw system.img
          fi
          file system.img | grep -q "ext[2-4]\|f2fs" || { echo "Invalid system.img"; exit 1; }

      - name: Convert to VNDKLITE
        run: |
          if [ ! -f vndklite/lite-adapter.sh ]; then
            echo "lite-adapter.sh not found in vndklite/"
            exit 1
          fi
          bash vndklite/lite-adapter.sh $ARCH system.img.raw

      - name: Upload result
        uses: actions/upload-artifact@v4
        with:
          name: vndklite-gsi
          path: s.img
